// Login
export const LOGIN_TYPE = 'LOGIN_TYPE';

export const Access_Type = 'Access_Type';

export const SIGNUP_TYPE = 'SIGNUP_TYPE';

export const GETCLIENT_TYPE = 'GETCLIENT_TYPE';

export const GET_ENV_DETAILS_TYPE = 'GET_ENV_DETAILS_TYPE';

export const GET_MODULE_TYPE = 'GET_MODULE_TYPE';

export const GET_SERVICES_By_MODULE = 'GET_SERVICES_By_MODULE';

export const GET_APILIST_BYVERSION = 'GET_APILIST_BYVERSION';

export const GET_VERSIONS_SERVICE = 'GET_VERSIONS_SERVICE';

export const GET_ALLPACKAGES_TYPE = 'GET_ALLPACKAGES_TYPE';

export const GET_PURCHASED_PACKAGES_TYPE = 'GET_PURCHASED_PACKAGES_TYPE';

export const GET_PACKAGE_BY_ID = 'GET_PACKAGE_BY_ID';

export const ADD_PACKAGE_TYPE = 'ADD_PACKAGE_TYPE';

export const ADD_PAYMENT_TYPE = 'ADD_PAYMENT_TYPE';

export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP';

export const PUT_PACKAGE_TYPE = 'PUT_PACKAGE_TYPE';

export const REQUEST_COUNT = 'REQUEST_COUNT';

export const GET_HISTORY_TYPE = 'GET_HISTORY_TYPE';

export const DELETE_PACKAGE_BY_ID_TYPE = 'DELETE_PACKAGE_BY_ID_TYPE';

export const LOGOUT_TYPE = 'LOGOUT_TYPE';

export const GET_SIGNUP = 'GET_SIGNUP';

export const GET_ALLPARTNERS_TYPE = 'GET_ALLPARTNERS_TYPE';

export const PUT_PARTNER_PACKAGE_TYPE = 'PUT_PARTNER_PACKAGE_TYPE';

export const ONBOARD_PARTNER_TYPE = 'ONBOARD_PARTNER_TYPE';

export const GET_TENANT_TYPE = 'GET_TENANT_TYPE';

export const FORGOTPASSWORD_TYPE = 'FORGOTPASSWORD_TYPE';
